# Generated by Django 4.1.4 on 2023-09-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('image', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
    ]
